### ISSUE TITLE
OptimizeImportsCommand causes "Invalid stub element" error

### ISSUE THREAD

**Issue by dhleong** [dhleong/intellivim#11]
Repro:
- Open RunnableMain.java
- Add a line like `Arrays.asList()`
- Run `:JavaOptimizeImports`
- Notice IntelliJ spitting a lot of error toasts, and the following in the output:

```
[  37116]  ERROR - tellij.psi.stubs.StubIndexImpl - Invalid stub element type in index:
file: file:///Users/dhleong/IdeaProjects/IntelliVim/projects/runnable-project/src/org/intellivim/runnable/RunnableMain.java
psiElement: PsiImportStatement
requiredClass: interface com.intellij.psi.PsiClass
actualClass: class com.intellij.psi.impl.source.PsiImportStatementImpl
virtualFile: size:276; stamp:48355; modCount:1425826472000; fileType:JAVA; language:JAVA
document: size:276; stamp:48355; committed:true; saved:true
psiFile: size:276; stamp:48355; class:com.intellij.psi.impl.source.PsiJavaFileImpl; language:JAVA
fileAST: size:276; parsed:true
indexing info: indexed at 1425826472000 with size 276 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
	at com.intellij.psi.stubs.StubIndexImpl.reportStubPsiMismatch(StubIndexImpl.java:508)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:153)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:132)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerBase.findClasses(JavaFileManagerBase.java:94)
	at com.intellij.psi.impl.JavaPsiFacadeImpl$PsiElementFinderImpl.findClasses(JavaPsiFacadeImpl.java:293)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:144)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightClassUtil.checkDuplicateTopLevelClass(HighlightClassUtil.java:165)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitClass(HighlightVisitorImpl.java:395)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:483)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:136)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:312)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:397)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:318)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:173)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:388)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:230)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.runMainPasses(DaemonCodeAnalyzerImpl.java:255)
	at org.intellivim.core.command.problems.Problems$1.run(Problems.java:62)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at org.intellivim.core.command.problems.Problems.collectFrom(Problems.java:58)
	at org.intellivim.core.command.problems.Problems.collectFrom(Problems.java:45)
	at org.intellivim.core.command.problems.GetProblemsCommand.execute(GetProblemsCommand.java:25)
	at org.intellivim.CommandExecutor$3.run(CommandExecutor.java:145)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
	at org.intellivim.CommandExecutor.executeProjectCommand(CommandExecutor.java:141)
	at org.intellivim.CommandExecutor.access$100(CommandExecutor.java:24)
	at org.intellivim.CommandExecutor$2.run(CommandExecutor.java:131)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:238)
	at com.intellij.openapi.project.DumbServiceImpl.access$500(DumbServiceImpl.java:53)
	at com.intellij.openapi.project.DumbServiceImpl$IndexUpdateRunnable$1$3.run(DumbServiceImpl.java:420)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  37119]  ERROR - tellij.psi.stubs.StubIndexImpl - IntelliJ IDEA 13.1.6  Build #IC-135.1306 
[  37119]  ERROR - tellij.psi.stubs.StubIndexImpl - JDK: 1.7.0_45 
[  37119]  ERROR - tellij.psi.stubs.StubIndexImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[  37119]  ERROR - tellij.psi.stubs.StubIndexImpl - Vendor: Oracle Corporation 
[  37119]  ERROR - tellij.psi.stubs.StubIndexImpl - OS: Mac OS X 
[  37119]  ERROR - tellij.psi.stubs.StubIndexImpl - Last Action:  
[  37119]  ERROR - tellij.psi.stubs.StubIndexImpl - Current Command: intellivim-command 
[  37528]   WARN - j.ui.mac.MacMainFrameDecorator - no url bundle present. 
To use platform protocol handler to open external links specify required protocols in the mac app layout section of the build file
Example: args.urlSchemes = ["your-protocol"] will handle following links: your-protocol://open?file=file&line=line 
[  37701]  ERROR - tellij.psi.stubs.StubIndexImpl - Invalid stub element type in index:
file: file:///Users/dhleong/IdeaProjects/IntelliVim/projects/runnable-project/src/org/intellivim/runnable/RunnableMain.java
psiElement: PsiImportStatement
requiredClass: interface com.intellij.psi.PsiClass
actualClass: class com.intellij.psi.impl.source.PsiImportStatementImpl
virtualFile: size:276; stamp:48355; modCount:1425826472000; fileType:JAVA; language:JAVA
document: size:276; stamp:48355; committed:true; saved:true
psiFile: size:276; stamp:48355; class:com.intellij.psi.impl.source.PsiJavaFileImpl; language:JAVA
fileAST: size:276; parsed:true
indexing info: indexed at 1425826472000 with size 276 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
	at com.intellij.psi.stubs.StubIndexImpl.reportStubPsiMismatch(StubIndexImpl.java:508)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:153)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:132)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerBase.findClasses(JavaFileManagerBase.java:94)
	at com.intellij.psi.impl.JavaPsiFacadeImpl$PsiElementFinderImpl.findClasses(JavaPsiFacadeImpl.java:293)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:144)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightClassUtil.checkDuplicateTopLevelClass(HighlightClassUtil.java:165)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitClass(HighlightVisitorImpl.java:395)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:483)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:136)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:312)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:397)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:318)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:173)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:388)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:230)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.runMainPasses(DaemonCodeAnalyzerImpl.java:255)
	at org.intellivim.core.command.problems.Problems$1.run(Problems.java:62)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at org.intellivim.core.command.problems.Problems.collectFrom(Problems.java:58)
	at org.intellivim.core.command.problems.Problems.collectFrom(Problems.java:45)
	at org.intellivim.core.command.problems.GetProblemsCommand.execute(GetProblemsCommand.java:25)
	at org.intellivim.CommandExecutor$3.run(CommandExecutor.java:145)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
	at org.intellivim.CommandExecutor.executeProjectCommand(CommandExecutor.java:141)
	at org.intellivim.CommandExecutor.access$100(CommandExecutor.java:24)
	at org.intellivim.CommandExecutor$2.run(CommandExecutor.java:131)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:238)
	at com.intellij.openapi.project.DumbServiceImpl.access$500(DumbServiceImpl.java:53)
	at com.intellij.openapi.project.DumbServiceImpl$IndexUpdateRunnable$1$3.run(DumbServiceImpl.java:420)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  37702]  ERROR - tellij.psi.stubs.StubIndexImpl - IntelliJ IDEA 13.1.6  Build #IC-135.1306 
[  37702]  ERROR - tellij.psi.stubs.StubIndexImpl - JDK: 1.7.0_45 
[  37702]  ERROR - tellij.psi.stubs.StubIndexImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[  37702]  ERROR - tellij.psi.stubs.StubIndexImpl - Vendor: Oracle Corporation 
[  37702]  ERROR - tellij.psi.stubs.StubIndexImpl - OS: Mac OS X 
[  37702]  ERROR - tellij.psi.stubs.StubIndexImpl - Last Action:  
[  37702]  ERROR - tellij.psi.stubs.StubIndexImpl - Current Command: intellivim-command 
```

**Comment by dhleong** [comment]
I think `FileUtil.commitChanges()` can be ruled out; the `:Implement` command works well enough.

Possibly of note, deleting a class reference and doing `:JavaOptimizeImports` again (IE: removing the now-unused import) also causes a similar error:

```
[  99710]  ERROR - tellij.psi.stubs.StubIndexImpl - Invalid stub element type in index:
file: file:///Users/dhleong/IdeaProjects/IntelliVim/projects/runnable-project/src/org/intellivim/runnable/RunnableMain.java
psiElement: PsiModifierList:public
requiredClass: interface com.intellij.psi.PsiClass
actualClass: class com.intellij.psi.impl.source.PsiModifierListImpl
virtualFile: size:276; stamp:50473; modCount:1425827240000; fileType:JAVA; language:JAVA
document: size:276; stamp:50473; committed:true; saved:true
psiFile: size:276; stamp:50473; class:com.intellij.psi.impl.source.PsiJavaFileImpl; language:JAVA
fileAST: size:276; parsed:true
indexing info: indexed at 1425827240000 with size 276 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
	at com.intellij.psi.stubs.StubIndexImpl.reportStubPsiMismatch(StubIndexImpl.java:508)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:153)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:132)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerBase.findClasses(JavaFileManagerBase.java:94)
	at com.intellij.psi.impl.JavaPsiFacadeImpl$PsiElementFinderImpl.findClasses(JavaPsiFacadeImpl.java:293)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:144)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightClassUtil.checkDuplicateTopLevelClass(HighlightClassUtil.java:165)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitClass(HighlightVisitorImpl.java:395)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:483)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:136)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:312)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:397)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:403)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:318)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:173)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:400)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:388)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:230)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.runMainPasses(DaemonCodeAnalyzerImpl.java:255)
	at org.intellivim.core.command.problems.Problems$1.run(Problems.java:62)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at org.intellivim.core.command.problems.Problems.collectFrom(Problems.java:58)
	at org.intellivim.core.command.problems.Problems.collectFrom(Problems.java:45)
	at org.intellivim.core.command.problems.GetProblemsCommand.execute(GetProblemsCommand.java:25)
	at org.intellivim.CommandExecutor$3.run(CommandExecutor.java:145)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
	at org.intellivim.CommandExecutor.executeProjectCommand(CommandExecutor.java:141)
	at org.intellivim.CommandExecutor.access$100(CommandExecutor.java:24)
	at org.intellivim.CommandExecutor$2.run(CommandExecutor.java:131)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:238)
	at com.intellij.openapi.project.DumbServiceImpl.access$500(DumbServiceImpl.java:53)
	at com.intellij.openapi.project.DumbServiceImpl$IndexUpdateRunnable$1$3.run(DumbServiceImpl.java:420)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  99711]  ERROR - tellij.psi.stubs.StubIndexImpl - IntelliJ IDEA 13.1.6  Build #IC-135.1306 
[  99711]  ERROR - tellij.psi.stubs.StubIndexImpl - JDK: 1.7.0_45 
[  99711]  ERROR - tellij.psi.stubs.StubIndexImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[  99711]  ERROR - tellij.psi.stubs.StubIndexImpl - Vendor: Oracle Corporation 
[  99711]  ERROR - tellij.psi.stubs.StubIndexImpl - OS: Mac OS X 
[  99711]  ERROR - tellij.psi.stubs.StubIndexImpl - Last Action:  
[  99711]  ERROR - tellij.psi.stubs.StubIndexImpl - Current Command: intellivim-command 
```

**Comment by dhleong** [comment]
Hm. Commenting out the following code fixes it for the "removing unused import" case, but of course the import isn't removed by the command....

```java
        ImportOptimizer optimizer = new JavaImportOptimizer();
        if (optimizer.supports(psiFile)) {
            Runnable action = optimizer.processFile(psiFile);
            ApplicationManager.getApplication().runWriteAction(action);

            FileUtil.commitChanges(editor);
        }
```

Perhaps there's something missing in the `FileUtil.commitChanges()`?

**Comment by dhleong** [comment]
Adding calls to `Problems.ensureIndexesUpToDate(project);` appears to have no effect

**Comment by dhleong** [comment]
Since Google just released Preview 1 of their IntelliJ 14-based Android Studio, I'm just going to try to get this working on IntelliJ 14 and see if the newer codebase resolves this issue.
